const getPokemonSeed = (data) => {
  const pokemonSeed = data.pokemon.map(poke => (
  { 
    pokedex: poke.pokedex, 
    name: poke.name, 
    image: poke.image,
    blurb: poke.blurb,
    attack: poke.attack,
    defence: poke.defense,
    specialAttack: poke.specialAttack,
    specialDefence: poke.specialDefense,
    colour: poke.colour,
    evolutionURL: poke.evolutionURL,
    experience: poke.experience,
    height: poke.height,
    weight: poke.weight,
    speed: poke.speed,
    shape: poke.shape,
    happiness: poke.happiness,
    habitat: poke.habitat,
    hp: poke.hp,
    evolvesFrom: poke.evolvesFrom
  }
))

return pokemonSeed
}

const getTypeSeed = (data) => {
  const type = data.pokemon.map(poke => poke.type)
  const typeSeed = type.flat()

  const uniqueTypes = []

  const unique = typeSeed.filter(element => {
  const isDuplicate = uniqueTypes.includes(element.type);

  if (!isDuplicate) {
    uniqueTypes.push(element.type)
    return true
  }
  return false
})
return unique
}


const getAbilitySeed = (data) => {
  const abilities = data.pokemon.map(poke => poke.ability)
  const abilitySeed = abilities.flat()

  const uniqueAbilities = []

  const unique = abilitySeed.filter(element => {
  const isDuplicate = uniqueAbilities.includes(element.ability);

  if (!isDuplicate) {
    uniqueAbilities.push(element.ability)
    return true
  }
  return false
})
return unique
}

const TYPEID = {
  grass: 1,
  poison: 2,
  fire: 3,
  flying: 4,
  water: 5,
  bug: 6,
  normal: 7,
  electric: 8,
  ground: 9,
  fairy: 10,
  fighting: 11,
  psychic: 12,
  rock: 13,
  steel:14,
  ice: 15,
  ghost:16,
  dragon: 17,
  dark:18
}

const ABILITYID = {
  "overgrow": 1,
  "chlorophyll": 2,
  "blaze": 3,
  "solar-power": 4,
  "torrent": 5,
  "rain-dish": 6,
  "shield-dust": 7,
  "run-away": 8,
  "shed-skin": 9,
  "compound-eyes": 10,
  "tinted-lens": 11,
  "swarm": 12,
  "sniper": 13,
  "keen-eye": 14,
  "tangled-feet": 15,
  "big-pecks": 16,
  "guts": 17,
  "hustle": 18,
  "intimidate": 19,
  "unnerve": 20,
  "static": 21,
  "lightning-rod": 22,
  "sand-veil": 23,
  "sand-rush": 24,
  "poison-point": 25,
  "rivalry": 26,
  "sheer-force": 27,
  "cute-charm": 28,
  "magic-guard": 29,
  "friend-guard": 30,
  "unaware": 31,
  "flash-fire": 32,
  "drought": 33,
  "competitive": 34,
  "frisk": 35,
  "inner-focus": 36,
  "infiltrator": 37,
  "stench": 38,
  "effect-spore": 39,
  "dry-skin": 40,
  "damp": 41,
  "wonder-skin": 42,
  "arena-trap": 43,
  "sand-force": 44,
  "pickup": 45,
  "technician": 46,
  "limber": 47,
  "cloud-nine": 48,
  "swift-swim": 49,
  "vital-spirit": 50,
  "anger-point": 51,
  "defiant": 52,
  "justified": 53,
  "water-absorb": 54,
  "synchronize": 55,
  "no-guard": 56,
  "steadfast": 57,
  "gluttony": 58,
  "clear-body": 59,
  "liquid-ooze": 60,
  "rock-head": 61,
  "sturdy": 62,
  "flame-body": 63,
  "oblivious": 64,
  "own-tempo": 65,
  "regenerator": 66,
  "magnet-pull": 67,
  "analytic": 68,
  "early-bird": 69,
  "thick-fat": 70,
  "hydration": 71,
  "ice-body": 72,
  "sticky-hold": 73,
  "poison-touch": 74,
  "shell-armor": 75,
  "skill-link": 76,
  "overcoat": 77,
  "levitate": 78,
  "cursed-body": 79,
  "weak-armor": 80,
  "insomnia": 81,
  "forewarn": 82,
  "hyper-cutter": 83,
  "soundproof": 84,
  "aftermath": 85,
  "harvest": 86,
  "battle-armor": 87,
  "reckless": 88,
  "unburden": 89,
  "iron-fist": 90,
  "neutralizing-gas": 91,
  "natural-cure": 92,
  "serene-grace": 93,
  "healer": 94,
  "leaf-guard": 95,
  "scrappy": 96,
  "water-veil": 97,
  "illuminate": 98,
  "filter": 99,
  "mold-breaker": 100,
  "moxie": 101,
  "rattled": 102,
  "imposter": 103,
  "adaptability": 104,
  "anticipation": 105,
  "volt-absorb": 106,
  "quick-feet": 107,
  "trace": 108,
  "download": 109,
  "pressure": 110,
  "immunity": 111,
  "snow-cloak": 112,
  "marvel-scale": 113,
  "multiscale": 114,
  "super-luck": 115,
  "magic-bounce": 116,
  "plus": 117,
  "huge-power": 118,
  "sap-sipper": 119,
  "drizzle": 120,
  "speed-boost": 121,
  "prankster": 122,
  "shadow-tag": 123,
  "telepathy": 124,
  "light-metal": 125,
  "contrary": 126,
  "pickpocket": 127,
  "honey-gather": 128,
  "magma-armor": 129,
  "moody": 130,
  "suction-cups": 131,
  "sand-stream": 132,
  "poison-heal": 133,
  "truant": 134,
  "wonder-guard": 135,
  "normalize": 136,
  "stall": 137,
  "heavy-metal": 138,
  "pure-power": 139,
  "minus": 140,
  "rough-skin": 141,
  "simple": 142,
  "solid-rock": 143,
  "white-smoke": 144,
  "toxic-boost": 145,
  "storm-drain": 146,
  "forecast": 147,
  "color-change": 148,
  "protean": 149,
  "air-lock": 150,
  "flower-gift": 151,
  "flare-boost": 152,
  "klutz": 153,
  "heatproof": 154,
  "snow-warning": 155,
  "motor-drive": 156,
  "slow-start": 157,
  "bad-dreams": 158,
  "multitype": 159,
  "victory-star": 160,
  "zen-mode": 161,
  "mummy": 162,
  "defeatist": 163,
  "illusion": 164,
  "iron-barbs": 165,
  "slush-rush": 166,
  "turboblaze": 167,
  "teravolt": 168,
  "bulletproof": 169,
  "magician": 170,
  "cheek-pouch": 171,
  "gale-wings": 172,
  "flower-veil": 173,
  "symbiosis": 174,
  "grass-pelt": 175,
  "fur-coat": 176,
  "stance-change": 177,
  "aroma-veil": 178,
  "sweet-veil": 179,
  "tough-claws": 180,
  "mega-launcher": 181,
  "strong-jaw": 182,
  "refrigerate": 183,
  "pixilate": 184,
  "gooey": 185,
  "fairy-aura": 186,
  "dark-aura": 187,
  "aura-break": 188,
  "long-reach": 189,
  "liquid-voice": 190,
  "stakeout": 191,
  "battery": 192,
  "dancer": 193,
  "schooling": 194,
  "merciless": 195,
  "stamina": 196,
  "water-bubble": 197,
  "corrosion": 198,
  "fluffy": 199,
  "queenly-majesty": 200,
  "triage": 201,
  "receiver": 202,
  "wimp-out": 203,
  "emergency-exit": 204,
  "water-compaction": 205,
  "innards-out": 206,
  "rks-system": 207,
  "shields-down": 208,
  "comatose": 209,
  "disguise": 210,
  "dazzling": 211,
  "berserk": 212,
  "steelworker": 213,
  "electric-surge": 214,
  "psychic-surge": 215,
  "grassy-surge": 216,
  "misty-surge": 217,
  "full-metal-body": 218,
  "shadow-shield": 219,
  "beast-boost": 220,
  "prism-armor": 221,
  "soul-heart": 222,
  "libero": 223,
  "mirror-armor": 224,
  "cotton-down": 225,
  "ball-fetch": 226,
  "steam-engine": 227,
  "ripen": 228,
  "sand-spit": 229,
  "gulp-missile": 230,
  "propeller-tail": 231,
  "punk-rock": 232,
  "steely-spirit": 233,
  "perish-body": 234,
  "screen-cleaner": 235,
  "wandering-spirit": 236,
  "ice-scales": 237,
  "power-spot": 238,
  "ice-face": 239,
  "hunger-switch": 240,
  "stalwart": 241,
  "intrepid-sword": 242,
  "dauntless-shield": 243,
  "unseen-fist": 244,
  "transistor": 245,
  "dragons-maw": 246,
  "chilling-neigh": 247,
  "grim-neigh": 248,
}

module.exports = {
    getAbilitySeed,
    getPokemonSeed,
    getTypeSeed,
    TYPEID,
    ABILITYID
}