import Head from 'next/head'
import prisma from '../../lib/prisma'
import Detail from '../../components/Detail'
import styles from '../../styles/Page.module.css'
import { capitalise } from '../../lib/utils'

export const getStaticPaths = async () => {
  const pokemonNames = await prisma.pokemon.findMany({
    select: { 
      name: true 
    }
  })

  const paths = pokemonNames.map(pokeName => ({
    params: { 
      pokemon: pokeName.name.toLowerCase()
    }
  }))

  return { paths, fallback: true }
}

export const getStaticProps = async ({ params }) => {
    const onePokemon = await prisma.pokemon.findUnique({
      where: {
        name: capitalise(params.pokemon)
      },
      include: {
        type: true,
        ability: true,
      },
})
    return {
    props : { onePokemon }
  }
      }

 const PokemonDetail = ({ onePokemon }) => {
   console.log(onePokemon)

  return (
    <div className={styles.container}>
      <Head>
        <title>{onePokemon.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Detail pokemon={onePokemon}/>
      </main>
    </div>
  )
}

export default PokemonDetail