import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import Detail from '../components/Detail'
import styles from '../styles/Page.module.css'

const router = useRouter()
const { pid } = router.query

const getStaticProps = async () => {}

const getStaticPaths = async () => {}


 const Details = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Detail />
      </main>
    </div>
  )
}

export default Details