import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


 const Details = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>PokemonDetails</h1>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Details